export const REVIEWS = [
  {
    id: 1,
    name: "Marcus Webb",
    location: "Austin, TX",
    avatar: "/rev1.jpg",
    rating: 5,
    date: "2025-01-18",
    text: "Ordered the Icons Shire set and it arrived double-boxed with every bag numbered and sealed. Genuinely the best condition I've received a set in — will be back for the Balrog Book Nook next.",
  },
  {
    id: 2,
    name: "Priya Nandakumar",
    location: "Leicester, UK",
    avatar: "/rev2.jpg",
    rating: 5,
    date: "2025-03-04",
    text: "The subtheme browsing made it so easy to find exactly the Friends Vet sets my daughter wanted. Checkout was quick and the tracking updates were spot on.",
  },
  {
    id: 3,
    name: "Diego Alvarez",
    location: "Madrid, Spain",
    avatar: "/rev3.jpg",
    rating: 4,
    date: "2025-04-22",
    text: "Great range of minifigures, especially the Star Wars Mandalorian line. Shipping to Spain took a couple of extra days but customer support kept me updated throughout.",
  },
  {
    id: 4,
    name: "Freya Lindqvist",
    location: "Gothenburg, Sweden",
    avatar: "/rev4.jpg",
    rating: 5,
    date: "2025-06-11",
    text: "I've bought from three other LEGO resellers and LegoBricksLink is the only one that lists piece count, designer, and packaging details up front. That transparency sold me.",
  },
  {
    id: 5,
    name: "Tunde Adeyemi",
    location: "Lagos, Nigeria",
    avatar: "/rev5.jpg",
    rating: 5,
    date: "2025-07-29",
    text: "The Creator 3-in-1 Surprising Spider was exactly as described, box in mint condition. Added a second item to cart after checkout and it merged into my order instantly.",
  },
  {
    id: 6,
    name: "Claire Boucher",
    location: "Montréal, Canada",
    avatar: "/rev6.jpg",
    rating: 5,
    date: "2025-09-15",
    text: "Their City Formula 1 collection is unbeatable — I picked up the full Garage set plus two driver figures and everything shipped together, well padded.",
  },
  {
    id: 7,
    name: "Haruto Sasaki",
    location: "Osaka, Japan",
    avatar: "/rev7.jpg",
    rating: 4,
    date: "2025-11-02",
    text: "Very clean site to navigate, themes to subthemes to products in three clicks. Would love more payment options but overall a smooth experience.",
  },
  {
    id: 8,
    name: "Amara Okafor",
    location: "Bristol, UK",
    avatar: "/rev8.jpg",
    rating: 5,
    date: "2026-01-20",
    text: "Bought the Seasonal Gingerbread House as a gift — arrived a week early, beautifully packed. The reviews on the product pages helped me decide between two sets.",
  },
  {
    id: 9,
    name: "Lucas Ferreira",
    location: "Porto, Portugal",
    avatar: "/rev9.jpg",
    rating: 5,
    date: "2026-04-08",
    text: "Best minifigure selection I've found online, and the accessory details listed on each card meant zero surprises when the Marvel figures arrived.",
  },
  {
    id: 10,
    name: "Isla Thompson",
    location: "Wellington, New Zealand",
    avatar: "/rev10.jpg",
    rating: 5,
    date: "2026-06-30",
    text: "Ordered internationally and honestly expected delays — instead it was faster than most local shops. LegoBricksLink has earned a repeat customer.",
  },
];
